### ISSUE TITLE
Missing Ingress pathType with k8s >=1.22

### ISSUE THREAD

**Issue by PhilDulac** [provectus/kafka-ui#1448]
**Describe the bug**

When installing the helm chart on K8s version >= 1.22 with ingress enabled, the path type is missing and gives the following message:
`Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Ingress.spec.rules[0].http.paths[0]): missing required field "pathType" in io.k8s.api.networking.v1.HTTPIngressPath`

**Set up**

** Needs to be done on a k8s cluster version 1.22 or greater.

Enable the ingress and specify a path in values.yaml:
```
kafka-ui:
  ingress:
    enabled: true
    path: /
```

**Steps to Reproduce**

1. `helm install chart-name .`

**Expected behavior**

Chart is successfully installed is correctly formatted ingress.

**Comment by Haarolean** [comment]
@PhilDulac hey, thanks for reaching out. This has been fixed in `master`-labeled image, we'll also get a minor release with this change to update the charts on artifacthub.

**Comment by RobinQu** [comment]
Still missing pathType if  only `kafka-ui.ingress.path`  is configured.
