### ISSUE TITLE
Web UI ignores SERVER_SERVLET_CONTEXT_PATH environment variable after #2153

### ISSUE THREAD

**Issue by ashevtsov-wawa** [provectus/kafka-ui#2346]
**Describe the bug**
Before #2153 was merged Kafka UI used to render pages using base path as set by `SERVER_SERVLET_CONTEXT_PATH` (i.e. `/kafka-ui` in our case).
After #2153 `index.html` returns links to resources without the base path

**Set up**
How do you run the app? Please provide as much info as possible:
Docker container created from `provectuslabs/kafka-ui:1b71ccb9755041e18ff540d5c57318243b38876d` image

**Steps to Reproduce**

1. Create Docker container passing `SERVER_SERVLET_CONTEXT_PATH=/kafka-ui` environment variable
   ```
   docker run -p 8080:8080 \
        -e KAFKA_CLUSTERS_0_NAME=local \
        -e KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092 \
        -e SERVER_SERVLET_CONTEXT_PATH=/kafka-ui \
        -d provectuslabs/kafka-ui:1b71ccb9755041e18ff540d5c57318243b38876d
   ```
2. Open main page - `curl -sS http://localhost:8080/kafka-ui/`
3. Observe that links returned in the main page do not include `/kafka-ui/` prefix
Example:
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="icon" href="/favicon.ico" sizes="any"><!-- 32×32 -->
    <link rel="icon" href="/favicon/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/favicon/apple-touch-icon.png"><!-- 180×180 -->
    <link rel="manifest" href="/manifest.json" />

    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>UI for Apache Kafka</title>
    <script type="text/javascript">
      window.basePath = "";
    </script>
    <script type="module" crossorigin src="/assets/index.e3fb6b5d.js"></script>
    <link rel="modulepreload" href="/assets/venod.29ff7209.js">
    <link rel="modulepreload" href="/assets/lodash.146e3116.js">
    <link rel="stylesheet" href="/assets/index.ea5bd143.css">
  </head>
  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="root"></div>

  </body>
</html>
```

**Expected behavior**
Links should include prefix specified in `SERVER_SERVLET_CONTEXT_PATH` environment variable
Example:
```
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <link rel="icon" href="./favicon.ico" sizes="any">
    <link rel="icon" href="./favicon/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="./favicon/apple-touch-icon.png">
    <link rel="manifest" href="./manifest.json" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <title>UI for Apache Kafka</title>
    <script type="text/javascript">window.basePath = "/kafka-ui"</script>
    <script defer="defer" src="/kafka-ui/static/js/main.26d94848.js"></script>
    <link href="/kafka-ui/static/css/main.bf915e18.css" rel="stylesheet">
</head>

<body><noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="root"></div>
</body>

</html>
```

**Additional context**
The image from the prior commit works as expected - `provectuslabs/kafka-ui:d859dd6b3f4bcdcc9143a2e02695eca95be0fd9f`
```
❯ docker run -p 8080:8080 -e KAFKA_CLUSTERS_0_NAME=local -e KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092 -e SERVER_SERVLET_CONTEXT_PATH=/kafka-ui -d provectuslabs/kafka-ui:d859dd6b3f4bcdcc9143a2e02695eca95be0fd9f
Unable to find image 'provectuslabs/kafka-ui:d859dd6b3f4bcdcc9143a2e02695eca95be0fd9f' locally
d859dd6b3f4bcdcc9143a2e02695eca95be0fd9f: Pulling from provectuslabs/kafka-ui
59bf1c3509f3: Already exists
50806c9650be: Already exists
d47367f99f01: Pull complete
Digest: sha256:15152c3d122a76cbb182452db16fed24004d5bc1f38ce41e637eed7dafa9b93f
Status: Downloaded newer image for provectuslabs/kafka-ui:d859dd6b3f4bcdcc9143a2e02695eca95be0fd9f
5d107f9f29e9f9d848a92944bb93fc231169357910104687266a20509d4984d4
❯ curl -sS http://localhost:8080/kafka-ui/
<!doctype html><html lang="en"><head><meta charset="utf-8"/><link rel="icon" href="./favicon.ico" sizes="any"><link rel="icon" href="./favicon/icon.svg" type="image/svg+xml"><link rel="apple-touch-icon" href="./favicon/apple-touch-icon.png"><link rel="manifest" href="./manifest.json"/><meta name="viewport" content="width=device-width,initial-scale=1"/><title>UI for Apache Kafka</title><script type="text/javascript">window.basePath="/kafka-ui"</script><script defer="defer" src="/kafka-ui/static/js/main.6f6697ad.js"></script><link href="/kafka-ui/static/css/main.d0feaa17.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div></body></html>
```

**Comment by Haarolean** [comment]
Hey, thanks for reaching out. We'll take a look ASAP.

**Comment by Haarolean** [comment]
Done, the fix is available in `master`-labeled image. We had to get rid of dynamic chunks loading but we'll think of something later.

**Comment by Amarmandal** [comment]
@Haarolean When we use AUTH_TYPE as "Login Form" the sigin page do not load bootstrap css. It is still not returning the base path set to SERVER_SERVLET_CONTEXT_PATH. 

![image](https://github.com/provectus/kafka-ui/assets/31056357/08ea6059-eeb7-46ae-b826-91c72e675517)

**Comment by Haarolean** [comment]
@Amarmandal https://github.com/provectus/kafka-ui/issues/4178

**Comment by alba-ado** [comment]
Any updates?

**Comment by germanosin** [comment]
Me and @Haarolean  no longer support this repo, don't you mind to post this to https://github.com/kafbat/kafka-ui
