### ISSUE TITLE
"Oldest first" message view shows no records, but keeps polling partitions

### ISSUE THREAD

**Issue by burpeenerd** [provectus/kafka-ui#4434]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

Since updating to v.0.7.2, kafka-ui does not show any records when "Oldest first" (default) view is selected. It just seems to consume the topic by polling all the partitions (exactly like it would when a filter is selected), but no records are shown. After the whole topic has been consumed, "No records found" message is shown.
* "Newest first" is working, for the very same topic
* It seems to be no general issue, as "Oldest first" is working for some other topics on the same broker, and for others not. We didn't find any correlation in topic size or settings between the 'working' and the 'non working' topics

### Expected behavior

"Oldest first" should work for all topics

### Your installation details

* image: 'v0.7.2' (latest release), but tried 'master' as well
* chart: '0.7.6'
* App config did not change during update from v0.7.1 to v0.7.2

### Steps to reproduce

* on an affected Topic, just switch to the "Message" tab, which should show records "immediately" (consuming from earliest)

### Screenshots

During consumption of the whole topic (on "Oldest first")
<img width="1587" alt="image" src="https://github.com/provectus/kafka-ui/assets/95344112/cdc86b44-adfd-47e2-8065-710bfc2948a5">
After consumption (and no messages where found)
<img width="1593" alt="image" src="https://github.com/provectus/kafka-ui/assets/95344112/470840ae-1c80-464d-9fc5-4d181ad7294d">

### Logs

[kafka-ui.log](https://github.com/provectus/kafka-ui/files/14988482/kafka-ui.log)

### Additional context

* from checking the logs it seems, like the Consumer being in a constant loop of "Resuming partitions" (of the topic), being "Assigned to partition(s)", Seeking to offsets, Pausing partitions and cycling back to "Resuming" again...

**Comment by Haarolean** [comment]
Hi @marcmesh! Despite the new "release", this repo is not really maintained (see #4255). 
We've fixed all the issues related to messages in https://github.com/kafbat/kafka-ui, will be happy to hear your feedback.
Release link: [v1.0.0](https://github.com/kafbat/kafka-ui/releases/tag/v1.0.0)

**Comment by burpeenerd** [comment]
Thank you very much @Haarolean for pointing me to Kafbat UI. We will try out v1.0.0 as suggested and report back 🚀

**Comment by burpeenerd** [comment]
@Haarolean after migrating to Kafbat 1.0.0, the issue persists unfortunately :( (besides that Oldest and Newest are switched, which is a known and already fixed issue).
<img width="1661" alt="image" src="https://github.com/provectus/kafka-ui/assets/95344112/0b3d9873-8748-454f-a3a5-97a585635b30">
So how should I proceed, is "linking" this issue in https://github.com/kafbat/kafka-ui enough or should I replicate the issue there?
