### ISSUE TITLE
Wrong redirection path to topic resource

### ISSUE THREAD

**Issue by Schiavi91** [provectus/kafka-ui#898]
**Describe the bug**
In the "Consumers" view, if you select a consumer group and click on the link on the topic name (/ui/clusters/local/consumer-groups/my-consumer-group), you will be redirected to the wrong resource (/clusters/local/topics/my-topic instead of /ui/clusters/local/topics/my-topic)

**Set up**
Executed in the local environment with docker-compose.

**Steps to Reproduce**
1. Create a topic
2. Create a consumer that consume from the topic
3. Go to the "Consumers" view and select the newly created consumer-group
4. Click on the link on the topic name
5. Check the path that is requested

**Expected behavior**
Request to correct path (/ui/clusters/local/topics/my-topic).

**Comment by germanosin** [comment]
Hi, @Schiavi91. Thx for creating this issue We'll try to fix in the next minor version.

**Comment by GneyHabub** [comment]
@Schiavi91 the issue is already solved in master. Could you please pull the latest docker image or pull the latest version of the repo?

**Comment by Schiavi91** [comment]
Ok, thanks @GneyHabub. I checked and with the latest version of the docker image the problem still exist but I confirm that, in the docker image with tag "master", the problem is solved.
